[package]
name = "debug-try"
version = "0.1.0"
authors = ["Fredrik Østrem <frx.apps@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[[bin]]
name = "debug-try"

[dependencies]
syn = { version = "0.15", features = [ "full", "visit-mut", "extra-traits" ] }
quote = "0.6"
proc-macro2 = "0.4"
